config/routes.rb
  match 'generate_form_to_edit_sales_order_customer/:sales_order_id' => 'sales_orders#generate_form_to_edit_sales_order_customer', :as => :generate_form_to_edit_sales_order_customer
  match 'update_sales_order_customer/:sales_order_id' => 'sales_orders#update_sales_order_customer', :as => :update_sales_order_customer, :method => :post

=begin
  Create new vehicle from sales order
=end
  match 'new_vehicle_from_sales_order' => 'vehicles#new_vehicle_from_sales_order', :as => :new_vehicle_from_sales_order  
  match 'create_vehicle_from_sales_order' => 'vehicles#create_vehicle_from_sales_order', :as => :create_vehicle_from_sales_order, :method => :post 

=begin
  Adding Sales Entry
=end
  match 'generate_sales_entry_add_product_form' => 'sales_entries#generate_sales_entry_add_product_form', :as => :generate_sales_entry_add_product_form, :method => :post 
  match 'generate_sales_entry_add_service_form' => 'sales_entries#generate_sales_entry_add_service_form', :as => :generate_sales_entry_add_service_form, :method => :post 
  
  match 'create_service_sales_entry/:sales_order_id' => 'sales_entries#create_service_sales_entry', :as => :create_service_sales_entry , :method => :post 

=begin
  Editing sales entry 
=end
  match 'update_sales_entry/:sales_order_id/sales_entry/:id' => 'sales_entries#update_sales_entry', :as => :update_sales_entry, :method => :post 
  match 'update_sales_entry_service/:sales_order_id/sales_entry/:id' => 'sales_entries#update_sales_entry_service', :as => :update_sales_entry_service, :method => :post 
  
   
=begin
  DELETE Sales Entry
=end
  match 'delete_sales_entry_from_sales_order/:sales_order_id' => 'sales_entries#delete_sales_entry_from_sales_order', :as => :delete_sales_entry_from_sales_order, :method => :post 


=begin
  CONFIRM SALES ORDER 
=end
  match 'confirm_sales_order/:sales_order_id' => "sales_orders#confirm_sales_order", :as => :confirm_sales_order, :method => :post 
  match 'delete_sales_order/:sales_order_id' => "sales_orders#delete_sales_order", :as => :delete_sales_order, :method => :post 
  
=begin
  Special for Service: add vehicle and items 
=end
  match 'generate_form_to_add_service_sales_entry_details/:sales_entry_id' => 'sales_entries#generate_form_to_add_service_sales_entry_details', :as => :generate_form_to_add_service_sales_entry_details
  match 'create_service_sales_entry_details/:sales_entry_id' => 'sales_entries#create_service_sales_entry_details', :as => :create_service_sales_entry_details, :method => :post 

=begin
  Printing Sales Invoice
=end
  match 'print_sales_invoice/:sales_order_id' => 'sales_orders#print_sales_invoice', :as => :print_sales_invoice
##################################################
##################################################
######### Create PURCHASE ORDER + ENTRIES 
##################################################
##################################################


=begin
  Adding Purchase Entry
=end
  match 'generate_purchase_entry_add_product_form' => 'purchase_entries#generate_purchase_entry_add_product_form', :as => :generate_purchase_entry_add_product_form, :method => :post 
 

=begin
  Editing Purchase Entry
=end
  match 'update_purchase_entry/:purchase_order_id/purchase_entry/:id' => 'purchase_entries#update_purchase_entry', :as => :update_purchase_entry, :method => :post

=begin
  DELETE PurchaseEntry
=end
  match 'delete_purchase_entry_from_purchase_order/:purchase_order_id' => 'purchase_entries#delete_purchase_entry_from_purchase_order', :as => :delete_purchase_entry_from_purchase_order, :method => :post 


=begin
  CONFIRM  PURCHASE ORDER
=end
  match 'confirm_purchase_order/:purchase_order_id' => "purchase_orders#confirm_purchase_order", :as => :confirm_purchase_order, :method => :post 
  match 'delete_purchase_order/:purchase_order_id' => "purchase_orders#delete_purchase_order", :as => :delete_purchase_order, :method => :post 

##################################################
##################################################
######### Create SALES_RETURN + ENTRIES 
##################################################
##################################################


=begin
  Adding Sales Return Entry
=end
  match 'generate_sales_return_entry_add_product_form' => 'sales_return_entries#generate_sales_return_entry_add_product_form', :as => :generate_sales_return_entry_add_product_form, :method => :post 


=begin
  Editing Sales Return Entry
=end
  match 'update_sales_return_entry/:sales_return_id/sales_return_entry/:id' => 'sales_return_entries#update_sales_return_entry', :as => :update_sales_return_entry, :method => :post

=begin
  DELETE Sales Return Entry
=end
  match 'delete_sales_return_entry_from_sales_return/:sales_return_id' => 'sales_return_entries#delete_sales_return_entry_from_sales_return', :as => :delete_sales_return_entry_from_sales_return, :method => :post 


=begin
  CONFIRM  Sales Return 
=end
  match 'confirm_sales_return/:sales_return_id' => "sales_returns#confirm_sales_return", :as => :confirm_sales_return, :method => :post 
  match 'delete_sales_return/:sales_return_id' => "sales_returns#delete_sales_return", :as => :delete_sales_return, :method => :post


=begin
  Printing Sales Invoice
=end
  match 'print_sales_return/:sales_return_id' => 'sales_returns#print_sales_return', :as => :print_sales_return
  
####################################################################################################
####################################################################################################
############################ =>         Master Data                    #############################
####################################################################################################
#################################################################################################### 
   
##################################################
##################################################
######### EMPLOYEE PERFORMANCE THROUGH SERVICE ITEMS    + EMPLOYEE
##################################################
##################################################
  match 'service_done_by_employee/:employee_id' => 'service_items#service_done_by_employee', :as => :service_done_by_employee
  match 'update_employee/:employee_id' => 'employees#update_employee', :as => :update_employee , :method => :post 
  match 'delete_employee' => 'employees#delete_employee', :as => :delete_employee , :method => :post 
   
##################################################
##################################################
######### VENDOR
##################################################
##################################################
  match 'update_vendor/:vendor_id' => 'vendors#update_vendor', :as => :update_vendor , :method => :post 
  match 'delete_vendor' => 'vendors#delete_vendor', :as => :delete_vendor , :method => :post 
  
##################################################
##################################################
######### CATEGORY
##################################################
##################################################
  match 'update_category/:category_id' => 'categories#update_category', :as => :update_category , :method => :post 
  match 'delete_category' => 'categories#delete_category', :as => :delete_category , :method => :post
  
##################################################
##################################################
######### Service CATEGORY
##################################################
##################################################
  match 'update_service_category/:service_category_id' => 'service_categories#update_service_category', :as => :update_service_category , :method => :post 
  match 'delete_service_category' => 'service_categories#delete_service_category', :as => :delete_service_category , :method => :post
  
##################################################
##################################################
######### Service COMPONENT
##################################################
##################################################
  match 'update_service_component/:service_id/service_component/:id' => 'service_components#update_service_component', :as => :update_service_component , :method => :post 
  match 'delete_service_component/:service_id' => 'service_components#delete_service_component', :as => :delete_service_component , :method => :post


##################################################
##################################################
######### Service COMPATIBILITY
##################################################
##################################################
  match 'update_compatibility/:service_component_id/compatibility/:id' => 'compatibilities#update_compatibility', :as => :update_compatibility , :method => :post 
  match 'delete_compatibility/:service_component_id' => 'compatibilities#delete_compatibility', :as => :delete_compatibility , :method => :post

  
##################################################
##################################################
######### ITEM
##################################################
##################################################
  match 'update_item/:item_id' => 'items#update_item', :as => :update_item , :method => :post 
  match 'delete_item' => 'items#delete_item', :as => :delete_item , :method => :post
  
##################################################
##################################################
######### SERVICE
##################################################
##################################################
  match 'update_service/:service_id' => 'services#update_service', :as => :update_service , :method => :post 
  match 'delete_service' => 'services#delete_service', :as => :delete_service , :method => :post
  
##################################################
##################################################
######### CUSTOMER
##################################################

app/models/purchase_entry.rb
class PurchaseEntry < ActiveRecord::Base
  attr_accessible :item_id,  :price_per_piece, :quantity
  belongs_to :purchase_order 
  belongs_to :item 
  
  def update_total_purchase_price 
    self.total_purchase_price = self.price_per_piece *  self.quantity
    self.save 
  end
  
  def delete 
    if self.purchase_order.is_confirmed 
      return nil
    end
    
    self.is_deleted = true 
    self.save   
  end
  
  def update_item(quantity, price_per_piece) 
    return nil if self.purchase_order.is_confirmed?
    
    if not quantity.present? or quantity <=  0
      self.errors.add(:quantity , "Quantity harus setidaknya 1" ) 
      return self
    end
     
    if not price_per_piece.present? or price_per_piece <=  BigDecimal('0')
      self.errors.add(:price_per_piece , "Harga jual harus lebih besar dari 0 rupiah" ) 
      return self
    end
    
    self.quantity = quantity 
    self.price_per_piece = price_per_piece
    self.total_purchase_price = quantity  * price_per_piece 
    self.save
    
    return self
  end
  
  def create_stock_entry(employee)
    new_stock_entry = StockEntry.new 
    item = self.item 
    
    new_stock_entry.creator_id = employee.id
    new_stock_entry.quantity = self.quantity
    new_stock_entry.base_price_per_piece  = self.price_per_piece
    
    
    new_stock_entry.item_id  =  item.id 
    
    
    
    new_stock_entry.entry_case =  STOCK_ENTRY_CASE[:purchase]
    new_stock_entry.source_document = self.class.to_s 
    new_stock_entry.source_document_id = self.id 
    new_stock_entry.save 
    
     
    
    # where is the stock mutation ?
    StockMutation.create(
      :quantity            => self.quantity  ,
      :stock_entry_id      =>  new_stock_entry.id ,
      :creator_id          =>  employee.id ,
      :source_document_entry_id  =>  self.id   ,
      :source_document_id  =>  self.purchase_order_id  ,
      :source_document_entry     =>  self.class.to_s,
      :source_document    =>  self.purchase_order.class.to_s,
      :mutation_case      => MUTATION_CASE[:purchase_order],
      :mutation_status => MUTATION_STATUS[:addition],
      :item_id => item.id
    )
    
    
     
    item.add_stock_and_recalculate_average_cost_post_stock_entry_addition( new_stock_entry )
    
    return new_stock_entry
    
  end
  
  
  def stock_mutations
    StockMutation.where( 
      :source_document_entry_id  =>  self.id ,
      :source_document_id  =>  self.purchase_order_id  ,
      :source_document_entry     =>  self.class.to_s,
      :source_document    =>  self.purchase_order.class.to_s,
      :mutation_case      => MUTATION_CASE[:purchase_order],
      :mutation_status => MUTATION_STATUS[:addition],
      :item_id =>  self.entry_id  ,
      :item_status => ITEM_STATUS[:ready]
    ).order("created_at ASC")
  end
  
  def stock_entries
    stock_entry_id_list  = self.stock_mutations.map{|x| x.stock_entry_id }.uniq 
    StockEntry.where(:id =>stock_entry_id_list ).order("created_at ASC")
  end
  
  
end

app/controllers/purchase_entries_controller.rb
class PurchaseEntriesController < ApplicationController
  def new
    @purchase_order = PurchaseOrder.find_by_id params[:purchase_order_id]
    
    add_breadcrumb "Create Invoice", 'new_purchase_order_url'
    set_breadcrumb_for @group_loan, 'new_purchase_order_purchase_entry_url' + "(#{@purchase_order.id})", 
                "#{@purchase_order.code}"
  end
  
  def generate_purchase_entry_add_product_form
    @item=  Item.find_by_id params[:selected_item_id]
    @purchase_order = PurchaseOrder.find_by_id params[:purchase_order_id]
    @new_object = PurchaseEntry.new
  end
  
  def create
    @purchase_order = PurchaseOrder.find_by_id params[:purchase_order_id]
    @item = Item.find_by_id params[:item_id]
    @quantity = params[:purchase_entry][:quantity].to_i
    @price_per_piece =  BigDecimal( params[:purchase_entry][:price_per_piece] )
    
    @has_past_item =  @purchase_order.has_purchase_entry_for_item?(@item) 
    
    
    @purchase_entry =   @purchase_order.add_purchase_entry_item( @item,    
                                                        @quantity, 
                                                        @price_per_piece )
                          
    @has_no_errors  = @purchase_entry.errors.messages.length == 0  
  end
  
  def edit
    @purchase_order = PurchaseOrder.find_by_id params[:purchase_order_id]
    @purchase_entry =  @purchase_order.active_purchase_entries.where(:id => params[:id]).first
    @item = @purchase_entry.item 
  end
  
  def update_purchase_entry
    @purchase_order = PurchaseOrder.find_by_id params[:purchase_order_id]
    @purchase_entry =  @purchase_order.active_purchase_entries.where(:id => params[:id]).first
    
    @quantity =  params[:purchase_entry][:quantity].to_i
    @price_per_piece =  BigDecimal( params[:purchase_entry][:price_per_piece] )
    
    @new_object = @purchase_entry.update_item( @quantity, @price_per_piece)
    @has_no_errors  = @new_object.errors.messages.length == 0  
    
    @item = @purchase_entry.item
  end
  
  def delete_purchase_entry_from_purchase_order
    @purchase_order = PurchaseOrder.find_by_id params[:purchase_order_id]
    @purchase_entry = @purchase_order.active_purchase_entries.where(:id => params[:object_to_destroy_id]).first
    @purchase_order.delete_purchase_entry( @purchase_entry )
  end
  
end

app/helpers/purchase_entries_helper.rb
module PurchaseEntriesHelper
end

app/views/purchase_entries/_action.html.erb
<table class="table table-bordered table-striped" id='action_button'> 
	<tbody>
		<tr>
			<td style='text-align:center;'>
				<%= link_to "Confirm", confirm_purchase_order_url(purchase_order), :class => "btn btn btn-primary", :id => "confirm" %> 
			</td>
			<td style='text-align:center;'>
				<%= link_to "Delete", '#', :class => "btn btn btn-tertiary", :id => "delete" %>  
			</td> 
		</tr>
 
	</tbody>
</table>

<div class="hidden" id="confirm_order">
  <%= form_for PurchaseEntry.new, :url => confirm_purchase_order_url(purchase_order)  do |f| %> 
  <% end %>
</div>

<div class="hidden" id="delete_order">
  <%= form_for PurchaseEntry.new, :url => delete_purchase_order_url(purchase_order)  do |f| %> 
  <% end %>
</div>

app/views/purchase_entries/_entry_creator.html.erb
<%= render :partial => "purchase_entries/purchase_entry_trigger_form", :locals => {
	:purchase_order => purchase_order 
} %> 
<div id='add_product_form_wrapper'> 
</div>

app/views/purchase_entries/_post_confirm_action.html.erb
<table class="table table-bordered table-striped" id='action_button'> 
	<tbody>
		<tr>
			<td style='text-align:center;'>
					<a  class="btn btn btn-primary">Confirmed</a>	 	
			</td> 
		</tr>
 
	</tbody>
</table>

app/views/purchase_entries/_purchase_entry_trigger_form.html.erb
<%= simple_form_for :purchase_entry, { url: generate_purchase_entry_add_product_form_url, 
			:html => {:id=>"add_product_trigger_form" } } do |f| %>
  <%= f.input :search_item_id , :label => "Item"  %> 
	<%=	 hidden_field_tag 'selected_item_id', '' %> 
	<%=	 hidden_field_tag 'purchase_order_id', "#{purchase_order.id}" %> 
	<%= hidden_field_tag 'search_item_url', "#{search_item_url}"  %>
<% end %>

app/views/purchase_entries/_purchase_order_summary.html.erb
<table class="table table-bordered table-striped table-highlight" id='table_form'>
	<thead>
		<tr>
			<th  style='text-align:center;'>Invoice Pembelian No.: <b><%= purchase_order.code %></b></th>  
		</tr>
	</thead>
	<tbody>
		<tr>
			<td> 
			   Vendor:  
						<span class="label label-success"><%= purchase_order.vendor.name %></span> 
					
					<% if not purchase_order.is_confirmed? %>
						<%= link_to root_url, :class =>"edit_entry", :style => "cursor:pointer; text-decoration:none;" do %>
							<i class='icon-edit'></i>Edit
						<% end %>
					<% end %>
			</td>
	 
		</tr>
		<tr>
		</tr>
	</tbody>
</table>

app/views/purchase_entries/_purchased_items.html.erb
<table class="table table-bordered table-striped table-highlight" id='purchased_items'>
	<thead>
		<tr>
			<th> Item 	</th>
			<th> Quantity </th>
			<th> Unit Price  </th>
			<th> Total Price </th>
			<% if not purchase_order.is_confirmed? %>
				<th style='text-align:center;' colspan='2'>Action</th>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% purchase_order.active_purchase_entries.each do |purchase_entry| %>
			<%= render :partial => 'purchase_entries/purchase_order/entry', :locals => {
				:purchase_entry => purchase_entry ,
				:purchase_order => purchase_order
			}%>
			
		<% end %>
		
	</tbody>
</table>

app/views/purchase_entries/create.js.erb
$(document).ready(function(){
	var $form = $("#add_product_form");
	
	$form.spin(false); 

	<% if @has_past_item %>
		$("#purchase_entry_search_item_id").tokenInput("clear"); 
		$form.remove();
		
		
		$.msgbox("Sudah ada item <%= @item.name %> di purchase order. Silakan Edit", 
					{type: "error"});
	<% end %>

	<% if not @has_past_item and  @has_no_errors  %>
		// clean the search item
		$("#purchase_entry_search_item_id").tokenInput("clear");
		// clean the add product form
		$form.remove(); 
		
		<% new_entry  = escape_javascript(  render :partial => 'purchase_entries/purchase_order/entry', :locals => {
			:purchase_entry => @purchase_entry ,
			:purchase_order => @purchase_order 
		} )%>
		
	 $("#purchased_items tbody").append('<%= new_entry %>');
	
	 $.msgbox("Berhasil menambahkan item: <%= @item.name %>", 
					{type: "info"});
	
		<% new_total_purchase  = escape_javascript(  render :partial => 'purchase_entries/purchase_order/total_purchase', :locals => { 
			:purchase_order => @purchase_order 
		} )%>

		$("#total_purchase").replaceWith('<%= new_total_purchase %>');
		
		
	<% elsif not @has_past_item and not @has_no_errors %>
		<% new_form = escape_javascript(  render :partial => "purchase_entries/purchase_order/add_product_form", :locals => {
	    :new_object => @purchase_entry , 
			:url => purchase_order_purchase_entries_url(@purchase_order) ,
			:item => @item
	  })%>
		//replace the form, show the edit
		$form.replaceWith("<%= new_form %>"); 
		
		$.msgbox("Error dalam menambahkan item: <%= @item.name %>", 
					{type: "error"});
	<% end %>
 
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/purchase_entries/delete_purchase_entry_from_purchase_order.js.erb
$(document).ready(function(){
	
	var $row = $("#entry-<%= @purchase_entry.id %>")
	$row.spin(false); 
	
	$row.remove(); 
	
	$.msgbox("Berhasil menghapus item: <%= @purchase_entry.item.name %>");
	
	<% new_total_purchase  = escape_javascript(  render :partial => 'purchase_entries/purchase_order/total_purchase', :locals => { 
		:purchase_order => @purchase_order 
	} )%>
	
	$("#total_purchase").replaceWith('<%= new_total_purchase %>');
	
});

app/views/purchase_entries/edit.js.erb
$(document).ready(function(){
	  
		<% new_form = escape_javascript(  render :partial => "purchase_entries/purchase_order/edit_product_form", :locals => {
	    :new_object => @purchase_entry , 
			:url => update_purchase_entry_url(@purchase_order, @purchase_entry) ,
			:item => @item
	  })%>
 
	$("#editEntry .modal-body").append('<%= new_form %>');
	
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/purchase_entries/generate_purchase_entry_add_product_form.js.erb
$(document).ready(function(){
	var $form = $("#add_product_trigger_form");
	
	$form.spin(false);
	
	
	
	<% new_form = escape_javascript(  render :partial => "purchase_entries/purchase_order/add_product_form", :locals => {
    :new_object => @new_object , 
		:url => purchase_order_purchase_entries_url(@purchase_order) ,
		:item => @item
  })%>


	var $add_product_form=  $("#add_product_form");
	var $form_wrapper = $("#add_product_form_wrapper");
	
	if($add_product_form.length == 0 ){
		$form_wrapper.append('<%= new_form %>');
	}else {
		$add_product_form.replaceWith('<%= new_form %>');
	}

	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/purchase_entries/new.html.erb
<%= render :partial => "layouts/masthead" ,:locals => {
	:title => "Daftar Pembelian",
	:description => "Tambah Daftar Pembelian"
}%>

<%= create_breadcrumb(@breadcrumbs).html_safe %>

<div id="content">
	<div class="container"> 
		<div class="row"> 
			<div class="span8">  
				<%= render :partial => "purchase_entries/purchase_order_summary" , :locals => {
					:purchase_order => @purchase_order
				}%>
				
				<%= render :partial => "purchase_entries/purchased_items" , :locals => {
					:purchase_order => @purchase_order
				}%> 
				
				
				
				
				
				<%= render :partial => "purchase_entries/purchase_order/total_purchase" , :locals => {
					:purchase_order => @purchase_order
				}%>
				
				
				
			</div> <!-- /.span8 -->
			
			
			<div class="span4">
				
				<% if not @purchase_order.is_confirmed? %>
					<%= render :partial => 'purchase_entries/action', :locals => {
						:purchase_order => @purchase_order 
					} %>
				<% else %>
					<%= render :partial => 'purchase_entries/post_confirm_action', :locals => {
						:purchase_order => @purchase_order 
					} %>
				<% end %>
				 
				
			
				
				<hr />
				
				<% if not @purchase_order.is_confirmed? %> 
					<%= render :partial => "purchase_entries/entry_creator" , :locals => {
						:purchase_order => @purchase_order 
					}%>
				<% end %>
				
				
		 
			</div> <!-- /.span4 -->
		</div> <!-- /.row -->
		
		<div class='row'>
		</div><!--  /.row, for displaying the latest StockMigration performed --> 
	</div> <!-- /.container -->
</div> <!-- /#content --> 

<div class="modal fade hide" id="editEntry">
  <div class="modal-header">
    <h3>Edit Sales Entry</h3>
  </div>
  <div class="modal-body"> 
	<!-- content -->
  </div>
  <div class="modal-footer">
    <!-- <a href="javascript:;" class="btn" data-dismiss="modal">Close</a> -->
		<a  class="btn modal_closer"  >Close</a>
  </div>
</div>


<div class="hidden" id="delete_entry_form_wrapper">
  <%= form_for PurchaseEntry.new, :url =>delete_purchase_entry_from_purchase_order_url(@purchase_order)   do |f| %>
    <%= hidden_field_tag 'object_to_destroy_id' , ''  %> 
  <% end %>
</div>


<% content_for :additional_js do %> 
  <%= javascript_include_tag "jquery.tokeninput", 
													"common_order/entry_creation"  	%>
	
	<script type='text/javascript'>
		$(document).ready(function() {
				var $search_box = $("#purchase_entry_search_item_id");
				var $form = $search_box.parents("form"); 
				var search_item_url = $("#search_item_url").val(); 
		    $search_box.tokenInput( search_item_url , {
						propertyToSearch: "name",
						tokenLimit: 1, 
		        onAdd: function (item) {
								$form.spin("large", "black"); 
								$("#selected_item_id").attr( 'value',  item['id'] );

								$.ajax({
								      url: $form.attr("action"),
								      type: "POST",
								      data: $form.serialize(),
								      dataType: 'script',
								      success: function(response){ 

								      }
								    }); 
		        } ,
						onDelete: function(item){
							$("#add_product_form").remove();
						}
		    });

	 
		});
 	</script>
<% end %>

<% content_for :additional_css do %> 
  <%= stylesheet_link_tag "token-input", "token-input-facebook" 	%> 
<% end %>

app/views/purchase_entries/update_purchase_entry.js.erb
$(document).ready(function(){
	// remove the spin
	var $form = $("#edit_product_form");
	$form.spin(false); 
	
	// if update is successful
		// remove the form 
		// hide the modal 
		// update the row entry 
	// else
		// replace the form with the faulty one 
		// show all the error 
	
	
		<% if   @has_no_errors  %> 
			// clean the add product form
			$form.remove(); 

			<% new_entry  = escape_javascript(  render :partial => 'purchase_entries/purchase_order/entry', :locals => {
				:purchase_entry => @purchase_entry ,
				:purchase_order => @purchase_order 
			} )%>

			$("#entry-<%= @purchase_entry.id %>").replaceWith('<%= new_entry %>') 

			$.msgbox("Berhasil update item: <%= @item.name %>", 
						{type: "info"});

			var $modal = $("#editEntry");
			$modal.modal('hide');
			
			<% new_total_purchase  = escape_javascript(  render :partial => 'purchase_entries/purchase_order/total_purchase', :locals => { 
				:purchase_order => @purchase_order 
			} )%>

			$("#total_purchase").replaceWith('<%= new_total_purchase %>');



		<% elsif  not @has_no_errors %>
			<% new_form = escape_javascript(  render :partial => "purchase_entries/purchase_order/edit_product_form", :locals => {
		    :new_object => @purchase_entry , 
				:url => update_purchase_entry_url(@purchase_order, @purchase_entry)  ,
				:item => @item
		  })%>
			//replace the form, show the edit
			$form.replaceWith("<%= new_form %>"); 

			$.msgbox("Error dalam update item: <%= @item.name %>", 
						{type: "error"});
		<% end %>



		jQuery('.prevent_double_submit').preventDoubleSubmit(); 
});