config/routes.rb
Salmod::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end

  root :to => 'home#index'
  root :to => 'home#login'
  
  resources :companies
  match 'update_company/:id' => 'companies#update_company', :as => :update_company, :method => :post 
  
  
  resources :categories 
  resources :items 
  
  match 'search_item'  => 'items#search_item' , :as => :search_item
  match 'search_service' => 'services#search_service', :as => :search_service
  
  
  resources :stock_migrations 
  match 'generate_stock_migration'  => 'stock_migrations#generate_stock_migration' , :as => :generate_stock_migration, :method => :post 
  
  
  resources :stock_adjustments
  match 'generate_stock_adjustment'  => 'stock_adjustments#generate_stock_adjustment' , :as => :generate_stock_adjustment, :method => :post 
  
  resources :scrap_items
  match 'generate_scrap_item'  => 'scrap_items#generate_scrap_item' , :as => :generate_scrap_item, :method => :post 
  
  resources :exchange_scrap_items
  match 'generate_exchange_scrap_item'  => 'exchange_scrap_items#generate_exchange_scrap_item' , :as => :generate_exchange_scrap_item, :method => :post
  
  
  resources :purchase_returns
  match 'generate_purchase_return'  => 'purchase_returns#generate_purchase_return' , :as => :generate_purchase_return, :method => :post
  
  
  
=begin
  SERVICE RELATED
=end

  resources :service_categories do
    resources :services 
  end
  
  resources :services do
    resources :service_components 
  end
  
  resources :service_components do
    resources :compatibilities 
  end
=begin
  Creating Sales Order
=end
  resources :customers 
  resources :sales_orders do
    resources :sales_entries 
  end
  resources :purchase_orders do
    resources :purchase_entries  
  end
  
  resources :sales_returns do 
    resources :sales_return_entries
  end
  
  # employee management 
  resources :employees
  resources :vendors 
  resources :services
  resources :vehicles
  
  resources :stock_conversions do
    resources :conversion_entries 
    resources :convert_stocks
  end
  
  resources :convert_stocks
  
   

  match 'generate_sales_order'  => 'sales_orders#generate_sales_order' , :as => :generate_sales_order, :method => :post 
  match 'search_vehicle'  => 'vehicles#search_vehicle' , :as => :search_vehicle
  match 'search_customer' => "customers#search_customer", :as => :search_customer 
  match 'search_vendor' => "vendors#search_vendor", :as => :search_vendor 
  match 'search_sales_order' => "sales_orders#search_sales_order", :as => :search_sales_order 
  
  match 'search_sales_order_item/:sales_order_id' => 'items#search_sales_order_item', :as => :search_sales_order_item
  
 
  
=begin
  Edit sales order's customer
=end
  match 'generate_form_to_edit_sales_order_customer/:sales_order_id' => 'sales_orders#generate_form_to_edit_sales_order_customer', :as => :generate_form_to_edit_sales_order_customer
  match 'update_sales_order_customer/:sales_order_id' => 'sales_orders#update_sales_order_customer', :as => :update_sales_order_customer, :method => :post

=begin
  Create new vehicle from sales order
=end
  match 'new_vehicle_from_sales_order' => 'vehicles#new_vehicle_from_sales_order', :as => :new_vehicle_from_sales_order  
  match 'create_vehicle_from_sales_order' => 'vehicles#create_vehicle_from_sales_order', :as => :create_vehicle_from_sales_order, :method => :post 

=begin
  Adding Sales Entry
=end
  match 'generate_sales_entry_add_product_form' => 'sales_entries#generate_sales_entry_add_product_form', :as => :generate_sales_entry_add_product_form, :method => :post 
  match 'generate_sales_entry_add_service_form' => 'sales_entries#generate_sales_entry_add_service_form', :as => :generate_sales_entry_add_service_form, :method => :post 
  
  match 'create_service_sales_entry/:sales_order_id' => 'sales_entries#create_service_sales_entry', :as => :create_service_sales_entry , :method => :post 

=begin
  Editing sales entry 
=end
  match 'update_sales_entry/:sales_order_id/sales_entry/:id' => 'sales_entries#update_sales_entry', :as => :update_sales_entry, :method => :post 
  match 'update_sales_entry_service/:sales_order_id/sales_entry/:id' => 'sales_entries#update_sales_entry_service', :as => :update_sales_entry_service, :method => :post 
  
   
=begin
  DELETE Sales Entry
=end
  match 'delete_sales_entry_from_sales_order/:sales_order_id' => 'sales_entries#delete_sales_entry_from_sales_order', :as => :delete_sales_entry_from_sales_order, :method => :post 


=begin
  CONFIRM SALES ORDER 
=end
  match 'confirm_sales_order/:sales_order_id' => "sales_orders#confirm_sales_order", :as => :confirm_sales_order, :method => :post 
  match 'delete_sales_order/:sales_order_id' => "sales_orders#delete_sales_order", :as => :delete_sales_order, :method => :post 
  
=begin
  Special for Service: add vehicle and items 
=end
  match 'generate_form_to_add_service_sales_entry_details/:sales_entry_id' => 'sales_entries#generate_form_to_add_service_sales_entry_details', :as => :generate_form_to_add_service_sales_entry_details
  match 'create_service_sales_entry_details/:sales_entry_id' => 'sales_entries#create_service_sales_entry_details', :as => :create_service_sales_entry_details, :method => :post 

=begin
  Printing Sales Invoice
=end
  match 'print_sales_invoice/:sales_order_id' => 'sales_orders#print_sales_invoice', :as => :print_sales_invoice
##################################################
##################################################
######### Create PURCHASE ORDER + ENTRIES 
##################################################
##################################################


=begin
  Adding Purchase Entry
=end
  match 'generate_purchase_entry_add_product_form' => 'purchase_entries#generate_purchase_entry_add_product_form', :as => :generate_purchase_entry_add_product_form, :method => :post 
 

=begin
  Editing Purchase Entry
=end
  match 'update_purchase_entry/:purchase_order_id/purchase_entry/:id' => 'purchase_entries#update_purchase_entry', :as => :update_purchase_entry, :method => :post

=begin
  DELETE PurchaseEntry
=end
  match 'delete_purchase_entry_from_purchase_order/:purchase_order_id' => 'purchase_entries#delete_purchase_entry_from_purchase_order', :as => :delete_purchase_entry_from_purchase_order, :method => :post 


=begin
  CONFIRM  PURCHASE ORDER
=end
  match 'confirm_purchase_order/:purchase_order_id' => "purchase_orders#confirm_purchase_order", :as => :confirm_purchase_order, :method => :post 
  match 'delete_purchase_order/:purchase_order_id' => "purchase_orders#delete_purchase_order", :as => :delete_purchase_order, :method => :post 

##################################################
##################################################
######### Create SALES_RETURN + ENTRIES 
##################################################
##################################################


=begin
  Adding Sales Return Entry
=end
  match 'generate_sales_return_entry_add_product_form' => 'sales_return_entries#generate_sales_return_entry_add_product_form', :as => :generate_sales_return_entry_add_product_form, :method => :post 


=begin
  Editing Sales Return Entry
=end
  match 'update_sales_return_entry/:sales_return_id/sales_return_entry/:id' => 'sales_return_entries#update_sales_return_entry', :as => :update_sales_return_entry, :method => :post

=begin
  DELETE Sales Return Entry
=end
  match 'delete_sales_return_entry_from_sales_return/:sales_return_id' => 'sales_return_entries#delete_sales_return_entry_from_sales_return', :as => :delete_sales_return_entry_from_sales_return, :method => :post 


=begin
  CONFIRM  Sales Return 
=end
  match 'confirm_sales_return/:sales_return_id' => "sales_returns#confirm_sales_return", :as => :confirm_sales_return, :method => :post 
  match 'delete_sales_return/:sales_return_id' => "sales_returns#delete_sales_return", :as => :delete_sales_return, :method => :post


=begin
  Printing Sales Invoice
=end
  match 'print_sales_return/:sales_return_id' => 'sales_returns#print_sales_return', :as => :print_sales_return
  
####################################################################################################
####################################################################################################
############################ =>         Master Data                    #############################
####################################################################################################
#################################################################################################### 
   
##################################################
##################################################
######### EMPLOYEE PERFORMANCE THROUGH SERVICE ITEMS    + EMPLOYEE
##################################################
##################################################
  match 'service_done_by_employee/:employee_id' => 'service_items#service_done_by_employee', :as => :service_done_by_employee
  match 'update_employee/:employee_id' => 'employees#update_employee', :as => :update_employee , :method => :post 
  match 'delete_employee' => 'employees#delete_employee', :as => :delete_employee , :method => :post 
   
##################################################
##################################################
######### VENDOR
##################################################
##################################################
  match 'update_vendor/:vendor_id' => 'vendors#update_vendor', :as => :update_vendor , :method => :post 
  match 'delete_vendor' => 'vendors#delete_vendor', :as => :delete_vendor , :method => :post 
  
##################################################
##################################################
######### CATEGORY
##################################################
##################################################

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :name, :mobile_phone , :address 
  has_many :service_items, :through => :service_subcriptions
  has_many :service_subcriptions 
  
  after_create :add_employee_code
  validates_presence_of :name 
  validates_uniqueness_of :name , :case_sensitive => false 
  
  
  def add_employee_code
    year = DateTime.now.year 
    month = DateTime.now.month  
    total_employee_created_this_month = Employee.where(:year => year.to_i, :month => month.to_i).count  

    code =  'EM/' + year.to_s + '/' + 
                        month.to_s + '/' + 
                        (total_employee_created_this_month + 1 ).to_s
                        
    self.year = year 
    self.month = month 
    self.code = code
    self.save 
  end
  
  def self.active_employees
    Employee.where(:is_deleted => false ) 
  end
  
  def confirmed_services
    self.service_items.where(:is_confirmed => true , :is_deleted => false )
  end
  
  def confirmed_services_within_period(start_date, end_date) 
    # start_date and end_date is in UTC 
    # bring it to local time 
    start_date_utc =  start_date.to_time_in_current_zone.utc 
    end_date_utc   =  end_date.to_time_in_current_zone.utc 
    
    # bring this to local time 
    self.confirmed_services.where(:confirmed_datetime => start_date..end_date  ) 
    
  end
  
  def delete
    self.is_deleted = true 
    self.save 
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  
  
  def new 
    @objects = Employee.active_employees
    @new_object = Employee.new
    
    respond_to do |format|
      format.html   
      format.js  
    end 
  end
  
  def create
    
    @object = Employee.create(   params[:employee])
    
    
    if @object.valid?
      @new_object=  Employee.new
    else
      @new_object= @object
    end
  end
  
  def edit
    @employee = Employee.find_by_id params[:id] 
  end
  
  def update_employee
    @employee = Employee.find_by_id params[:employee_id] 
    @employee.update_attributes( params[:employee])
    @has_no_errors  = @employee.errors.messages.length == 0
  end
  
  def delete_employee
    @employee = Employee.find_by_id params[:object_to_destroy_id]
    @employee.delete 
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_entry.html.erb
<tr id="entry-<%= object.id %>">
	<td>
		<%= "#{object.code}" %>
	</td>
	<td>
		<%= "#{object.name}" %>
	</td>
	
	<td>
		<%= object.mobile_phone %>
	</td>
	
	<td>
		<%= object.address %>
	</td>
	
	<td>
		<%= link_to object.confirmed_services.count, service_done_by_employee_url( object )    %>
	</td>
	
	<td>
		<%= link_to root_url, :class =>"delete_entry", :style => "cursor:pointer; text-decoration:none;" do %>
			<i class='icon-remove'></i>Delete
		<% end %> 
	</td>

	<td>
		<%= link_to edit_employee_url(object), 
			:class =>"edit_entry modal-toggler", :style => "cursor:pointer; text-decoration:none;" do %>
			<i class='icon-edit'></i>Edit
		<% end %>
	</td>
</tr>

app/views/employees/_new_object_form.html.erb
<% if new_object.persisted? %>
	<% id = 'edit_object'%>
<% else %>
	<% id = 'new_object'%>
<% end %>
<%= simple_form_for( new_object, :url => url,
      :method => :post , 
      :html => {:class => "form-horizontal prevent_double_submit ajax-form   no_content_form",
        :id => "#{id}"}) do |f| %> 
			


  <%= f.input :name  , :input_html => {:class => "input-xlarge "}, 
  :label => "Nama" %>

	<%= f.input :mobile_phone  , :input_html => {:class => "input-xlarge "}, 
  :label => "Nomor Telpon" %>

	<%= f.input :address  , :input_html => {:class => "input-xlarge ", :rows => '5'}, 
  :label => "Alamat" %>
 

  <div class="form-actions">
	
		<% if new_object.persisted? %>
			<%= f.button :submit , :class => "btn btn-primary", :value=> "Update Employee" %>
		<% else %>
			<%= f.button :submit , :class => "btn btn-primary", :value=> "Create Employee" %>
		<% end %>
		
  </div>
<% end %>

app/views/employees/create.js.erb
$(document).ready(function(){ 
	
	var $modal = $("#newEntry");
	var $form = $("form", $modal );
	$form.spin(false);
	 
	
	<% new_form = escape_javascript(  render :partial => "employees/new_object_form", :locals => {
    :new_object => @new_object , 
		:url => employees_url,
  })%>


	

	<% if @object.valid? %>
		// show the growl. save. done. 
		<% new_entry = escape_javascript(  render :partial => "employees/entry", :locals => {
	    :object => @object  
	  })%>
		$("#tableview tbody").prepend('<%= new_entry %>');
		
		$.msgbox("Employee <b><%= @object.name %></b> is created.", 
					{type: "info"});
		$modal.modal('hide'); 
		$form.remove();
	<% else %>
		$form.replaceWith('<%= new_form %>');
		 $.msgbox("Fail to create new employee.", 
					{type: "error"});
	<% end %>
	
	// else, display error.. 
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/employees/delete_employee.js.erb
$(document).ready(function(){
	
	var $row = $("#entry-<%= @employee.id %>")
	$row.spin(false); 
	
	$row.remove(); 
	
	$.msgbox("Berhasil menghapus karyawan: <%= @employee.name %>");
	
	<%# new_total_purchase  = escape_javascript(  render :partial => 'sales_entries/sales_order/total_purchase', :locals => { 
		:sales_order => @sales_order 
	} )%>
	
	// $("#total_purchase").replaceWith('<%#= new_total_purchase %>');
	
});

app/views/employees/edit.js.erb
$(document).ready(function(){
	  
		<% new_form = escape_javascript(  render :partial => "employees/new_object_form", :locals => {
	    :new_object => @employee , 
			:url => update_employee_url(@employee)  
	  })%>
 
	$("#editEntry .modal-body").append('<%= new_form %>');
	
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/employees/index.html.erb
this is the index 

app/views/employees/new.html.erb
<%= render :partial => "layouts/masthead" ,:locals => {
	:title => "Employee",
	:description => "Add info to employee database"
}%>

<div id="content">

	<div class="container">
		
		
		<div class="row">
			
			<div class="span8">
				 
				<%= link_to new_employee_url, :class => "new_entry btn btn-primary" do %>
					<i class="icon-plus"></i>Karyawan Baru
				<% end %> 
				<hr />
				<%#= render :partial => "employees/new_object_form", :locals => {
					:new_object => @new_object , 
					:url => employees_url 
				}%>
 
				<table class="table table-bordered table-striped table-highlight" id='tableview'>
					<thead>
						<tr>
							<th>ID</th>
							<th>Name</th>
							<th>Contact</th> 
							<th>Address</th>
							<th>Total Service</th>
							<th colspan='2'>Action</th>
						</tr>
					</thead>
					<tbody> 
						<% @objects.each do |object| %>
							<%= render :partial =>  'employees/entry', :locals => {
								:object => object 
							} %> 
						<% end %>
					</tbody>
				</table>
			 
				
			</div> <!-- /.span8 -->
			
			
			<div class="span4">
				
						
				Total Karyawan: <%= Employee.active_employees.count %> <hr /> 
						
				
			</div> <!-- /.span4 -->
			
		</div> <!-- /.row -->
		
	
	</div> <!-- /.container -->

</div> <!-- /#content -->

<div class="modal fade hide" id="editEntry">
  <div class="modal-header">
    <h3>Edit Karyawan</h3>
  </div>
  <div class="modal-body"> 
	<!-- content -->
  </div>
  <div class="modal-footer">
    <!-- <a href="javascript:;" class="btn" data-dismiss="modal">Close</a> -->
		<a  class="btn modal_closer"  >Close</a>
  </div>
</div>

<div class="modal fade hide" id="newEntry">
  <div class="modal-header">
    <h3>Edit Karyawan</h3>
  </div>
  <div class="modal-body"> 
	<!-- content -->
  </div>
  <div class="modal-footer">
    <!-- <a href="javascript:;" class="btn" data-dismiss="modal">Close</a> -->
		<a  class="btn modal_closer"  >Close</a>
  </div>
</div>


<div class="hidden" id="delete_entry_form_wrapper">
  <%= form_for Employee.new, :url =>delete_employee_url , :method => :post   do |f| %>
    <%= hidden_field_tag 'object_to_destroy_id' , ''  %> 
  <% end %>
</div>


<% content_for :additional_js do %> 
	<%= javascript_include_tag "common_order/entry_creation"  	%>
<% end %>

app/views/employees/new.js.erb
$(document).ready(function(){
	  
		<% new_form = escape_javascript(  render :partial => "employees/new_object_form", :locals => {
	    :new_object => @new_object , 
			:url => employees_url 
	  })%>
 
	$("#newEntry .modal-body").append('<%= new_form %>');
	
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/employees/update_employee.js.erb
$(document).ready(function(){
	// remove the spin
	
	var $modal = $("#editEntry");
	var $form = $("form", $modal );
	$form.spin(false); 
	
	// if update is successful
		// remove the form 
		// hide the modal 
		// update the row entry 
	// else
		// replace the form with the faulty one 
		// show all the error 
	
	
		<% if   @has_no_errors  %> 
			// clean the add product form
			$form.remove(); 

			<% new_entry  = escape_javascript( render :partial =>  'employees/entry', :locals => {
				:object => @employee 
			} )%>

			$("#entry-<%= @employee.id %>").replaceWith('<%= new_entry %>') 

			$.msgbox("Berhasil update karyawan: <%= @employee.name %>", 
						{type: "info"});

			
			$modal.modal('hide'); 


		<% elsif  not @has_no_errors %> 
			<% new_form = escape_javascript(   render :partial => "employees/new_object_form", :locals => {
		    :new_object => @employee , 
				:url => update_employee_url(@employee)  
		  })%>
			//replace the form, show the edit
			$form.replaceWith("<%= new_form %>"); 

			$.msgbox("Error dalam update karyawan: <%= @employee.name %>", 
						{type: "error"});
		<% end %>



		jQuery('.prevent_double_submit').preventDoubleSubmit(); 
});