config/routes.rb
Salmod::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end

  root :to => 'home#index'
  root :to => 'home#login'
  
  resources :companies
  match 'update_company/:id' => 'companies#update_company', :as => :update_company, :method => :post 
  
  
  resources :categories 
  resources :items 
  
  match 'search_item'  => 'items#search_item' , :as => :search_item
  match 'search_service' => 'services#search_service', :as => :search_service
  
  
  resources :stock_migrations 
  match 'generate_stock_migration'  => 'stock_migrations#generate_stock_migration' , :as => :generate_stock_migration, :method => :post 
  
  
  resources :stock_adjustments
  match 'generate_stock_adjustment'  => 'stock_adjustments#generate_stock_adjustment' , :as => :generate_stock_adjustment, :method => :post 
  
  resources :scrap_items
  match 'generate_scrap_item'  => 'scrap_items#generate_scrap_item' , :as => :generate_scrap_item, :method => :post 
  
  resources :exchange_scrap_items
  match 'generate_exchange_scrap_item'  => 'exchange_scrap_items#generate_exchange_scrap_item' , :as => :generate_exchange_scrap_item, :method => :post
  
  
  resources :purchase_returns
  match 'generate_purchase_return'  => 'purchase_returns#generate_purchase_return' , :as => :generate_purchase_return, :method => :post
  
  
  
=begin
  SERVICE RELATED
=end

  resources :service_categories do
    resources :services 
  end
  
  resources :services do
    resources :service_components 
  end
  
  resources :service_components do
    resources :compatibilities 
  end
=begin
  Creating Sales Order
=end
  resources :customers 
  resources :sales_orders do
    resources :sales_entries 
  end
  resources :purchase_orders do
    resources :purchase_entries  
  end
  
  resources :sales_returns do 
    resources :sales_return_entries
  end
  
  # employee management 
  resources :employees
  resources :vendors 
  resources :services
  resources :vehicles
  
  resources :stock_conversions do
    resources :conversion_entries 
    resources :convert_stocks
  end
  
  resources :convert_stocks
  
   

  match 'generate_sales_order'  => 'sales_orders#generate_sales_order' , :as => :generate_sales_order, :method => :post 
  match 'search_vehicle'  => 'vehicles#search_vehicle' , :as => :search_vehicle
  match 'search_customer' => "customers#search_customer", :as => :search_customer 
  match 'search_vendor' => "vendors#search_vendor", :as => :search_vendor 
  match 'search_sales_order' => "sales_orders#search_sales_order", :as => :search_sales_order 
  
  match 'search_sales_order_item/:sales_order_id' => 'items#search_sales_order_item', :as => :search_sales_order_item
  
 
  
=begin
  Edit sales order's customer
=end
  match 'generate_form_to_edit_sales_order_customer/:sales_order_id' => 'sales_orders#generate_form_to_edit_sales_order_customer', :as => :generate_form_to_edit_sales_order_customer
  match 'update_sales_order_customer/:sales_order_id' => 'sales_orders#update_sales_order_customer', :as => :update_sales_order_customer, :method => :post

=begin
  Create new vehicle from sales order
=end
  match 'new_vehicle_from_sales_order' => 'vehicles#new_vehicle_from_sales_order', :as => :new_vehicle_from_sales_order  
  match 'create_vehicle_from_sales_order' => 'vehicles#create_vehicle_from_sales_order', :as => :create_vehicle_from_sales_order, :method => :post 

=begin
  Adding Sales Entry
=end
  match 'generate_sales_entry_add_product_form' => 'sales_entries#generate_sales_entry_add_product_form', :as => :generate_sales_entry_add_product_form, :method => :post 
  match 'generate_sales_entry_add_service_form' => 'sales_entries#generate_sales_entry_add_service_form', :as => :generate_sales_entry_add_service_form, :method => :post 
  
  match 'create_service_sales_entry/:sales_order_id' => 'sales_entries#create_service_sales_entry', :as => :create_service_sales_entry , :method => :post 

=begin
  Editing sales entry 
=end
  match 'update_sales_entry/:sales_order_id/sales_entry/:id' => 'sales_entries#update_sales_entry', :as => :update_sales_entry, :method => :post 
  match 'update_sales_entry_service/:sales_order_id/sales_entry/:id' => 'sales_entries#update_sales_entry_service', :as => :update_sales_entry_service, :method => :post 
  
   
=begin
  DELETE Sales Entry
=end
  match 'delete_sales_entry_from_sales_order/:sales_order_id' => 'sales_entries#delete_sales_entry_from_sales_order', :as => :delete_sales_entry_from_sales_order, :method => :post 


=begin
  CONFIRM SALES ORDER 
=end
  match 'confirm_sales_order/:sales_order_id' => "sales_orders#confirm_sales_order", :as => :confirm_sales_order, :method => :post 
  match 'delete_sales_order/:sales_order_id' => "sales_orders#delete_sales_order", :as => :delete_sales_order, :method => :post 
  
=begin
  Special for Service: add vehicle and items 
=end
  match 'generate_form_to_add_service_sales_entry_details/:sales_entry_id' => 'sales_entries#generate_form_to_add_service_sales_entry_details', :as => :generate_form_to_add_service_sales_entry_details
  match 'create_service_sales_entry_details/:sales_entry_id' => 'sales_entries#create_service_sales_entry_details', :as => :create_service_sales_entry_details, :method => :post 

=begin
  Printing Sales Invoice
=end
  match 'print_sales_invoice/:sales_order_id' => 'sales_orders#print_sales_invoice', :as => :print_sales_invoice
##################################################
##################################################
######### Create PURCHASE ORDER + ENTRIES 
##################################################
##################################################


=begin
  Adding Purchase Entry
=end
  match 'generate_purchase_entry_add_product_form' => 'purchase_entries#generate_purchase_entry_add_product_form', :as => :generate_purchase_entry_add_product_form, :method => :post 
 

=begin
  Editing Purchase Entry
=end
  match 'update_purchase_entry/:purchase_order_id/purchase_entry/:id' => 'purchase_entries#update_purchase_entry', :as => :update_purchase_entry, :method => :post

=begin
  DELETE PurchaseEntry
=end
  match 'delete_purchase_entry_from_purchase_order/:purchase_order_id' => 'purchase_entries#delete_purchase_entry_from_purchase_order', :as => :delete_purchase_entry_from_purchase_order, :method => :post 


=begin
  CONFIRM  PURCHASE ORDER
=end
  match 'confirm_purchase_order/:purchase_order_id' => "purchase_orders#confirm_purchase_order", :as => :confirm_purchase_order, :method => :post 
  match 'delete_purchase_order/:purchase_order_id' => "purchase_orders#delete_purchase_order", :as => :delete_purchase_order, :method => :post 

##################################################
##################################################
######### Create SALES_RETURN + ENTRIES 
##################################################
##################################################


=begin
  Adding Sales Return Entry
=end
  match 'generate_sales_return_entry_add_product_form' => 'sales_return_entries#generate_sales_return_entry_add_product_form', :as => :generate_sales_return_entry_add_product_form, :method => :post 


=begin
  Editing Sales Return Entry
=end
  match 'update_sales_return_entry/:sales_return_id/sales_return_entry/:id' => 'sales_return_entries#update_sales_return_entry', :as => :update_sales_return_entry, :method => :post

=begin
  DELETE Sales Return Entry
=end
  match 'delete_sales_return_entry_from_sales_return/:sales_return_id' => 'sales_return_entries#delete_sales_return_entry_from_sales_return', :as => :delete_sales_return_entry_from_sales_return, :method => :post 


=begin
  CONFIRM  Sales Return 
=end
  match 'confirm_sales_return/:sales_return_id' => "sales_returns#confirm_sales_return", :as => :confirm_sales_return, :method => :post 
  match 'delete_sales_return/:sales_return_id' => "sales_returns#delete_sales_return", :as => :delete_sales_return, :method => :post


=begin
  Printing Sales Invoice
=end
  match 'print_sales_return/:sales_return_id' => 'sales_returns#print_sales_return', :as => :print_sales_return
  
####################################################################################################
####################################################################################################
############################ =>         Master Data                    #############################
####################################################################################################
#################################################################################################### 
   
##################################################
##################################################
######### EMPLOYEE PERFORMANCE THROUGH SERVICE ITEMS    + EMPLOYEE
##################################################
##################################################
  match 'service_done_by_employee/:employee_id' => 'service_items#service_done_by_employee', :as => :service_done_by_employee
  match 'update_employee/:employee_id' => 'employees#update_employee', :as => :update_employee , :method => :post 
  match 'delete_employee' => 'employees#delete_employee', :as => :delete_employee , :method => :post 
   
##################################################
##################################################
######### VENDOR
##################################################
##################################################
  match 'update_vendor/:vendor_id' => 'vendors#update_vendor', :as => :update_vendor , :method => :post 
  match 'delete_vendor' => 'vendors#delete_vendor', :as => :delete_vendor , :method => :post 
  
##################################################
##################################################
######### CATEGORY
##################################################
##################################################

app/models/exchange_scrap_item.rb
class ExchangeScrapItem < ActiveRecord::Base
  # attr_accessible :title, :body
  
  belongs_to :item 
  validate :quantity_must_not_exceed_scrap_quantity
  
  def quantity_must_not_exceed_scrap_quantity
    item = self.item
    if self.quantity <= 0 or self.quantity > item.scrap 
      errors.add(:quantity , "Invalid Quantity. Setidaknya 1 dan tidak lebih dari #{item.scrap}") 
    end
  end
  
  
  def ExchangeScrapItem.generate_exchange_scrap_code( item)
    datetime  =  DateTime.now
    year = datetime.year 
    month = datetime.month   
    total_scrap_item_created_this_month = ExchangeScrapItem.where(:created_at => datetime.beginning_of_month..datetime.end_of_month   ).count  
    
    code =  'SCR/' + year.to_s + '/' + 
                        month.to_s + '/' + 
                        (total_scrap_item_created_this_month + 1 ).to_s 
    
    
    return code
  end
  
  
  def self.create_exchange_scrap( employee, item, quantity) 
    
    # return nil if quantity > item.scrap 
    
    new_ex_scrap_item = ExchangeScrapItem.new 
    new_ex_scrap_item.item_id = item.id 
    new_ex_scrap_item.quantity = quantity 
    new_ex_scrap_item.creator_id = employee.id 
    
    
    if item.is_deleted?  
      new_ex_scrap_item.errors.add(:item_id , "Invalid Item" ) 
      return new_ex_scrap_item
    end
    
    if quantity <= 0 or quantity > item.scrap 
      new_ex_scrap_item.errors.add(:quantity , "Invalid Quantity. Setidaknya 1 dan tidak lebih dari #{item.scrap}" ) 
      return new_ex_scrap_item
    end
    
    
    new_ex_scrap_item.code = ExchangeScrapItem.generate_exchange_scrap_code( item) 
    new_ex_scrap_item.save 
    
    ActiveRecord::Base.transaction do 
      StockMutation.deduct_scrap_add_ready_stock(
              employee, new_ex_scrap_item  ) 
    end
    
    return new_ex_scrap_item 
  end
  
=begin
  POST EXCHANGE: STOCK MUTATION TO DEDUCT scrap and ADD ready 
=end

  def stock_mutations_to_deduct_scrap_item 
    StockMutation.where( 
      :source_document_entry_id  =>  self.id  ,
      :source_document_id  =>  self.id  ,
      :source_document_entry     =>  self.class.to_s,
      :source_document    =>  self.class.to_s,
      :mutation_case      => MUTATION_CASE[:scrap_item_replacement],
      :mutation_status => MUTATION_STATUS[:deduction], 
      :item_status => ITEM_STATUS[:scrap]
    )
  end
  
  def stock_mutations_to_add_ready
    StockMutation.where( 
      :source_document_entry_id  =>  self.id  ,
      :source_document_id  =>  self.id  ,
      :source_document_entry     =>  self.class.to_s,
      :source_document    =>  self.class.to_s,
      :mutation_case      => MUTATION_CASE[:scrap_item_replacement],
      :mutation_status => MUTATION_STATUS[:addition], 
      :item_status => ITEM_STATUS[:ready]
    )
  end
end

app/controllers/exchange_scrap_items_controller.rb
class ExchangeScrapItemsController < ApplicationController
  def new
    @new_object = ExchangeScrapItem.new 
  end

  # only the view 
  def generate_exchange_scrap_item
    @new_object = ExchangeScrapItem.new 
    @item_id =  params[:selected_item_id] 
    @item = Item.find_by_id @item_id
  end

  def create 
    @item = Item.find_by_id params[:item_id]  
    quantity = params[:exchange_scrap_item][:quantity].to_i  

# create_exchange_scrap( employee, item, quantity) 
    # @object = StockMigration.create_item_migration(current_user , item, params[:stock_migration])
    @scrap_item =   ExchangeScrapItem.create_exchange_scrap( current_user, @item, quantity)  
    @object = @scrap_item  
    @item.reload 


    if @object.valid?
      @new_object=  ExchangeScrapItem.new 
    else
      @new_object= @object
    end

  end
end

app/helpers/exchange_scrap_items_helper.rb
module ExchangeScrapItemsHelper
end

app/views/exchange_scrap_items/_exchange_scrap_item_trigger_form.html.erb
<%= simple_form_for :signin, { url: generate_exchange_scrap_item_url, 
			:html => {:id=>"trigger_form" } } do |f| %>
  <%= f.input :search_item_id  %> 
	<%=	 hidden_field_tag 'selected_item_id', '' %> 
<% end %>

app/views/exchange_scrap_items/_exchange_scrap_summary.html.erb
<h5>
	Scrap Exchange Summary:  <b><%#= stock_adjustment.code %></b>
</h5>
<%= render :partial => "exchange_scrap_items/item_info_table", :locals => {
  :item =>  item
}%>

app/views/exchange_scrap_items/_item_info_table.html.erb
<table class="table table-bordered table-striped table-highlight" id='item_info'>
	<thead>
		<tr>
			<th colspan='2' style='text-align:center;'>Item Info</th> 
		</tr>
	</thead>
	<tbody>
	 	<tr>
			<td>Name</td>
			<td><%= item.name %></td>
		</tr>
		<tr>
			<td>Ready Stock</td>
			<td><%= item.ready %></td>
		</tr>
		
		<tr>
			<td>Scrap Stock</td>
			<td><%= item.scrap %></td>
		</tr>
	 
	</tbody>
</table>

app/views/exchange_scrap_items/_new_object_form.html.erb
<%= simple_form_for( new_object, :url => url,
      :method => :post , 
      :html => {:class => "form-horizontal prevent_double_submit ajax-form   no_content_form",
        :id => "new_object"}) do |f| %>

	<%#= f.input :parent_id , :label => "Super Category" %>
 	

 	<%= hidden_field_tag 'item_id', "#{item_id}"%>
	<%= f.input :quantity , :label => "Jumlah yang ditukar supplier", 
	 			:hint => "Jumlah yang rusak: #{item.scrap}"   %> 

  <div class="form-actions">
    <%= f.button :submit , :class => "btn btn-primary", :value=> "Create Exchange Scrap Item" %>
  </div>
<% end %>

app/views/exchange_scrap_items/create.js.erb
$(document).ready(function(){
	
	// if category creation is successful, append that category
	// show growl notification 
	
	var $form = $('#new_object'); 
	$form.spin(false);
	
	 
	<% if @object.valid? %>
	 
		
		
		// refresh the search  
		$("#signin_search_item_id").tokenInput("clear");
		
		// remove the display table 
		$("#item_info").remove(); 
		
		// remove the form for stock entry 
		$form.remove(); 
		
		// append the new stock migration into the last created stock migration. Just in case if he wants to edit
		
 
		<% summary_table = escape_javascript(  render :partial => "exchange_scrap_items/exchange_scrap_summary", :locals => {
	    :item =>  @item,
			:object => @object  
	  }) %>
		
		$.msgbox("<%= summary_table  %>", 
					{type: "info"});
		
					
	<% else %>
	
	 
		<% new_form = escape_javascript(  render :partial => "exchange_scrap_items/new_object_form", :locals => {
	    :new_object => @new_object , 
			:url => exchange_scrap_items_url ,
			:item_id => @item.id,
			:item => @item
	  })%>
	
	 
		$form.replaceWith('<%= new_form  %>');
	
		$.msgbox("Gagal menukar barang rusak", 
					{type: "error"});
	<% end %>
	
	// else, display error.. 
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/exchange_scrap_items/generate_exchange_scrap_item.js.erb
$(document).ready(function(){
	var $form = $("#trigger_form");  
	$form.spin(false);
	
	
		<% new_form = escape_javascript(  render :partial => "exchange_scrap_items/new_object_form", :locals => {
	    :new_object => @new_object , 
			:url => exchange_scrap_items_url ,
			:item_id => @item.id,
			:item => @item
	  })%>

		


		if($("#new_object").length != 0 ){ 
			$("#new_object").replaceWith("<%= new_form %>");
		}else if( $('#new_object').length == 0 ){ 
			$("#form_wrapper").append("<%= new_form %>"); 
		} 

		
		
		

	
	<% item_info_table = escape_javascript(  render :partial => "exchange_scrap_items/item_info_table", :locals => {
    :item =>  @item
  }) %>
	
	
	if($("#item_info").length != 0 ){ 
		$("#item_info").replaceWith("<%= item_info_table %>");
	}else if( $('#item_info').length == 0 ){ 
		$("#item_info_wrapper").append("<%= item_info_table %>"); 
	}
	
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/exchange_scrap_items/new.html.erb
<%= render :partial => "layouts/masthead" ,:locals => {
	:title => "Exchange Scrap Item",
	:description => "Scrap Item replacement from supplier"
}%>

<div id="content">

	<div class="container">
		
		 
		
		<div class="row">
			
					<ul id="myTab" class="nav nav-pills">
						<!-- <li class="active">
								<%= link_to "Stock Migration", new_stock_adjustment_url %>
							</li> -->
						<!-- <li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="#tab3" data-toggle="tab">@fat</a></li>
								<li><a href="#tab4" data-toggle="tab">@mdo</a></li>
							</ul>
						</li> -->
					</ul>
		
			
			
			<div class="span8">
			  
				
				
				<div id="form_wrapper">
				</div>
			</div> <!-- /.span8 -->
			
			
			<div class="span4">
				
				<%= render :partial => "exchange_scrap_items/exchange_scrap_item_trigger_form" %>
				
				<div id="item_info_wrapper">
					<!-- <div id='item_info'>
							</div> -->
				</div>
				
			</div> <!-- /.span4 -->
			
		</div> <!-- /.row -->
		
		
		<div class='row'>
		</div><!--  /.row, for displaying the latest StockMigration performed -->
		
	
	</div> <!-- /.container -->

</div> <!-- /#content -->

<% content_for :additional_js do %> 
  <%= javascript_include_tag "jquery.tokeninput" 	%> 

	<script type="text/javascript"> 
	
  $(document).ready(function() {
			var $search_box = $("#signin_search_item_id");
			var $form = $search_box.parents("form");
			
      $search_box.tokenInput( '<%= search_item_url %>' , {
					propertyToSearch: "name",
					tokenLimit: 1, 
          onAdd: function (item) {
							$form.spin("large", "black"); 
							$("#selected_item_id").attr( 'value',  item['id'] );
							
 							$.ajax({
							      url: $form.attr("action"),
							      type: "POST",
							      data: $form.serialize(),
							      dataType: 'script',
							      success: function(response){ 
								
							      }
							    }); 
          } ,
					onDelete: function(item){
						$("#new_object").remove();
						$("#item_info").remove();
					}
      });
  });

  </script>
<% end %>

<% content_for :additional_css do %> 
  <%= stylesheet_link_tag "token-input", "token-input-facebook" 	%> 
<% end %>