config/routes.rb
  match 'update_sales_entry/:sales_order_id/sales_entry/:id' => 'sales_entries#update_sales_entry', :as => :update_sales_entry, :method => :post 
  match 'update_sales_entry_service/:sales_order_id/sales_entry/:id' => 'sales_entries#update_sales_entry_service', :as => :update_sales_entry_service, :method => :post 
  
   
=begin
  DELETE Sales Entry
=end
  match 'delete_sales_entry_from_sales_order/:sales_order_id' => 'sales_entries#delete_sales_entry_from_sales_order', :as => :delete_sales_entry_from_sales_order, :method => :post 


=begin
  CONFIRM SALES ORDER 
=end
  match 'confirm_sales_order/:sales_order_id' => "sales_orders#confirm_sales_order", :as => :confirm_sales_order, :method => :post 
  match 'delete_sales_order/:sales_order_id' => "sales_orders#delete_sales_order", :as => :delete_sales_order, :method => :post 
  
=begin
  Special for Service: add vehicle and items 
=end
  match 'generate_form_to_add_service_sales_entry_details/:sales_entry_id' => 'sales_entries#generate_form_to_add_service_sales_entry_details', :as => :generate_form_to_add_service_sales_entry_details
  match 'create_service_sales_entry_details/:sales_entry_id' => 'sales_entries#create_service_sales_entry_details', :as => :create_service_sales_entry_details, :method => :post 

=begin
  Printing Sales Invoice
=end
  match 'print_sales_invoice/:sales_order_id' => 'sales_orders#print_sales_invoice', :as => :print_sales_invoice
##################################################
##################################################
######### Create PURCHASE ORDER + ENTRIES 
##################################################
##################################################


=begin
  Adding Purchase Entry
=end
  match 'generate_purchase_entry_add_product_form' => 'purchase_entries#generate_purchase_entry_add_product_form', :as => :generate_purchase_entry_add_product_form, :method => :post 
 

=begin
  Editing Purchase Entry
=end
  match 'update_purchase_entry/:purchase_order_id/purchase_entry/:id' => 'purchase_entries#update_purchase_entry', :as => :update_purchase_entry, :method => :post

=begin
  DELETE PurchaseEntry
=end
  match 'delete_purchase_entry_from_purchase_order/:purchase_order_id' => 'purchase_entries#delete_purchase_entry_from_purchase_order', :as => :delete_purchase_entry_from_purchase_order, :method => :post 


=begin
  CONFIRM  PURCHASE ORDER
=end
  match 'confirm_purchase_order/:purchase_order_id' => "purchase_orders#confirm_purchase_order", :as => :confirm_purchase_order, :method => :post 
  match 'delete_purchase_order/:purchase_order_id' => "purchase_orders#delete_purchase_order", :as => :delete_purchase_order, :method => :post 

##################################################
##################################################
######### Create SALES_RETURN + ENTRIES 
##################################################
##################################################


=begin
  Adding Sales Return Entry
=end
  match 'generate_sales_return_entry_add_product_form' => 'sales_return_entries#generate_sales_return_entry_add_product_form', :as => :generate_sales_return_entry_add_product_form, :method => :post 


=begin
  Editing Sales Return Entry
=end
  match 'update_sales_return_entry/:sales_return_id/sales_return_entry/:id' => 'sales_return_entries#update_sales_return_entry', :as => :update_sales_return_entry, :method => :post

=begin
  DELETE Sales Return Entry
=end
  match 'delete_sales_return_entry_from_sales_return/:sales_return_id' => 'sales_return_entries#delete_sales_return_entry_from_sales_return', :as => :delete_sales_return_entry_from_sales_return, :method => :post 


=begin
  CONFIRM  Sales Return 
=end
  match 'confirm_sales_return/:sales_return_id' => "sales_returns#confirm_sales_return", :as => :confirm_sales_return, :method => :post 
  match 'delete_sales_return/:sales_return_id' => "sales_returns#delete_sales_return", :as => :delete_sales_return, :method => :post


=begin
  Printing Sales Invoice
=end
  match 'print_sales_return/:sales_return_id' => 'sales_returns#print_sales_return', :as => :print_sales_return
  
####################################################################################################
####################################################################################################
############################ =>         Master Data                    #############################
####################################################################################################
#################################################################################################### 
   
##################################################
##################################################
######### EMPLOYEE PERFORMANCE THROUGH SERVICE ITEMS    + EMPLOYEE
##################################################
##################################################
  match 'service_done_by_employee/:employee_id' => 'service_items#service_done_by_employee', :as => :service_done_by_employee
  match 'update_employee/:employee_id' => 'employees#update_employee', :as => :update_employee , :method => :post 
  match 'delete_employee' => 'employees#delete_employee', :as => :delete_employee , :method => :post 
   
##################################################
##################################################
######### VENDOR
##################################################
##################################################
  match 'update_vendor/:vendor_id' => 'vendors#update_vendor', :as => :update_vendor , :method => :post 
  match 'delete_vendor' => 'vendors#delete_vendor', :as => :delete_vendor , :method => :post 
  
##################################################
##################################################
######### CATEGORY
##################################################
##################################################
  match 'update_category/:category_id' => 'categories#update_category', :as => :update_category , :method => :post 
  match 'delete_category' => 'categories#delete_category', :as => :delete_category , :method => :post
  
##################################################
##################################################
######### Service CATEGORY
##################################################
##################################################
  match 'update_service_category/:service_category_id' => 'service_categories#update_service_category', :as => :update_service_category , :method => :post 
  match 'delete_service_category' => 'service_categories#delete_service_category', :as => :delete_service_category , :method => :post
  
##################################################
##################################################
######### Service COMPONENT
##################################################
##################################################
  match 'update_service_component/:service_id/service_component/:id' => 'service_components#update_service_component', :as => :update_service_component , :method => :post 
  match 'delete_service_component/:service_id' => 'service_components#delete_service_component', :as => :delete_service_component , :method => :post


##################################################
##################################################
######### Service COMPATIBILITY
##################################################
##################################################
  match 'update_compatibility/:service_component_id/compatibility/:id' => 'compatibilities#update_compatibility', :as => :update_compatibility , :method => :post 
  match 'delete_compatibility/:service_component_id' => 'compatibilities#delete_compatibility', :as => :delete_compatibility , :method => :post

  
##################################################
##################################################
######### ITEM
##################################################
##################################################
  match 'update_item/:item_id' => 'items#update_item', :as => :update_item , :method => :post 
  match 'delete_item' => 'items#delete_item', :as => :delete_item , :method => :post
  
##################################################
##################################################
######### SERVICE
##################################################
##################################################
  match 'update_service/:service_id' => 'services#update_service', :as => :update_service , :method => :post 
  match 'delete_service' => 'services#delete_service', :as => :delete_service , :method => :post
  
##################################################
##################################################
######### CUSTOMER
##################################################
##################################################
  match 'update_customer/:customer_id' => 'customers#update_customer', :as => :update_customer , :method => :post 
  match 'delete_customer' => 'customers#delete_customer', :as => :delete_customer , :method => :post
  
##################################################
##################################################
######### VEHICLE
##################################################
##################################################
  match 'update_vehicle/:vehicle_id' => 'vehicles#update_vehicle', :as => :update_vehicle , :method => :post 
  match 'delete_vehicle' => 'vehicles#delete_vehicle', :as => :delete_vehicle , :method => :post
  match 'maintenance_histories/:vehicle_id' => 'service_items#maintenance_histories', :as => :maintenance_histories 
  
##################################################
##################################################
######### STOCK CONVERSION
##################################################
##################################################
  match 'update_stock_conversion/:vendor_id' => 'stock_conversions#update_stock_conversion', :as => :update_stock_conversion , :method => :post 

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id
  acts_as_nested_set
  
  has_many :items 
  
  validates_presence_of :name
  validate :unique_non_deleted_name 
  
  def unique_non_deleted_name
    current_service = self
     
     # claim.status_changed?
    if not current_service.name.nil? 
      if not current_service.persisted? and current_service.has_duplicate_entry?  
        errors.add(:name , "Sudah ada category  dengan nama sejenis" )  
      elsif current_service.persisted? and 
            current_service.name_changed?  and
            current_service.has_duplicate_entry?   
            # if duplicate entry is itself.. no error
            # else.. some error
            
          if current_service.duplicate_entries.count ==1  and 
              current_service.duplicate_entries.first.id == current_service.id 
          else
            errors.add(:name , "Sudah ada category  dengan nama sejenis" )  
          end 
      end
    end
  end
  
  def has_duplicate_entry?
    current_service=  self  
    self.class.find(:all, :conditions => ['lower(name) = :name and is_deleted = :is_deleted   ', 
                {:name => current_service.name.downcase, :is_deleted => false  }]).count != 0  
  end
  
  def duplicate_entries
    current_service=  self  
    return self.class.find(:all, :conditions => ['lower(name) = :name and is_deleted = :is_deleted  ', 
                {:name => current_service.name.downcase, :is_deleted => false }]) 
  end
  
  def create_sub_category( category_params ) 
    new_category = Category.create(:name => category_params[:name],
                              :parent_id => self.id ) 
    return new_category
  end
  
  
  def self.all_selectable_categories
    categories  = Category.where(:is_deleted => false ) .order("depth  ASC ")
    result = []
    categories.each do |category| 
      result << [ "#{category.name}" , 
                      category.id ]  
    end
    return result
  end
  
  def self.active_categories
    Category.where(:is_deleted => false).order("created_at DESC")
  end
  
  def delete
    parent = self.parent 
    if parent.nil?
      # can't be deleted from the base
      return nil
    end
    
    self.is_deleted = true
    self.save
    
    self.items.each do |item|
      item.category_id = parent.id
      item.save 
    end
    # what will happen to the item from this category? Go to the parent category 
  end
  
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @categories = Category.active_categories 
    @new_category = Category.new 
    @new_object = @new_category
    
    respond_to do |format|
      format.html # show.html.erb 
      format.js 
    end
  end
  
  def create
    base_category = Category.find_by_id params[:category][:parent_id]
    
    # sleep 5
    
    @object = base_category.create_sub_category( params[:category] ) 
    if @object.valid?
      @new_object=  Category.new
    else
      @new_object= @object
    end
    
  end
  
  def edit
    @category = Category.find_by_id params[:id] 
  end
  
  def update_category
    @category = Category.find_by_id params[:category_id] 
    @category.update_attributes( params[:category])
    @has_no_errors  = @category.errors.messages.length == 0
  end
  
  def delete_category
    @category = Category.find_by_id params[:object_to_destroy_id]
    @category.delete 
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_entry.html.erb
<tr id="entry-<%= object.id %>">
	<td>
		<%= object.name %>
	</td>
	
	<td>
		<%= object.items.count %>
	</td>
	
	<td>
		<%= link_to root_url, :class =>"delete_entry", :style => "cursor:pointer; text-decoration:none;" do %>
			<i class='icon-remove'></i>Delete
		<% end %> 
	</td>

	<td>
		<%= link_to edit_category_url(object), 
			:class =>"edit_entry modal-toggler", :style => "cursor:pointer; text-decoration:none;" do %>
			<i class='icon-edit'></i>Edit
		<% end %>
	</td>
</tr>

app/views/categories/_new_object_form.html.erb
<% if new_object.persisted? %>
	<% id = 'edit_object'%>
<% else %>
	<% id = 'new_object'%>
<% end %>

<%= simple_form_for( new_object, :url => url,
      :method => :post , 
      :html => {:class => "form-horizontal prevent_double_submit ajax-form   no_content_form",
        :id => "#{id}"}) do |f| %>

	<%#= f.input :parent_id , :label => "Super Category" %>
	
	<%= f.input :parent_id, :hint => "Parent Category", :label => "Parent Category" do %>
     <%= f.select :parent_id, 
         Category.all_selectable_categories %>
   <% end %>

  <%= f.input :name  , :input_html => {:class => "input-xlarge "}, 
  :label => "Name" %>


  <div class="form-actions">
		<% if new_object.persisted? %>
			<%= f.button :submit , :class => "btn btn-primary", :value=> "Update Category" %>
		<% else %>
			<%= f.button :submit , :class => "btn btn-primary", :value=> "Create Category " %>
		<% end %> 
  </div>
<% end %>

app/views/categories/create.js.erb
$(document).ready(function(){ 
	
	var $modal = $("#newEntry");
	var $form = $("form", $modal );
	$form.spin(false);
	 
	
	<% new_form = escape_javascript(   render :partial => "categories/new_object_form", :locals => {
    :new_object => @new_object , 
		:url => categories_url
  })%>


	

	<% if @object.valid? %>
		// show the growl. save. done. 
		<% new_entry = escape_javascript(  render :partial => "categories/entry", :locals => {
	    :object => @object  
	  })%>
		$("#tableview tbody").prepend('<%= new_entry %>');
		
		$.msgbox("Category <b><%= @object.name %></b> is created.", 
					{type: "info"});
		$modal.modal('hide'); 
		$form.remove();
	<% else %>
		$form.replaceWith('<%= new_form %>');
		 $.msgbox("Gagal membuat category baru.", 
					{type: "error"});
	<% end %>
	
	// else, display error.. 
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

 

app/views/categories/delete_category.js.erb
$(document).ready(function(){
	
	var $row = $("#entry-<%= @category.id %>")
	$row.spin(false); 
	
	$row.remove(); 
	
	$.msgbox("Berhasil menghapus Category: <%= @category.name %>");
	 
	
});

app/views/categories/edit.js.erb
$(document).ready(function(){
	  
		<% new_form = escape_javascript(  render :partial => "categories/new_object_form", :locals => {
	    :new_object => @category , 
			:url => update_category_url(@category)  
	  })%>
 
	$("#editEntry .modal-body").append('<%= new_form %>');
	
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/categories/new.html.erb
<%= render :partial => "layouts/masthead" ,:locals => {
	:title => "Categories Summary",
	:description => ""
}%>

<div id="content">

	<div class="container">
		
		
		<div class="row">
			
			<div class="span8">
				 
				<%= link_to new_category_url, :class => "new_entry btn btn-primary" do %>
					<i class="icon-plus"></i>Category Baru
				<% end %> 
				<hr />
				<%#= render :partial => "categories/new_object_form", :locals => {
					:new_object => @new_category , 
					:url => categories_url, 
				}%>

				
				
				<table class="table table-bordered table-striped table-highlight" id='tableview'>
					<thead>
						<tr>
							<th>Category Name</th>
							<th>Total Item</th> 
							<th colspan='2'>Action</th>
						</tr>
					</thead>
					<tbody>
						<% @categories.each do |category| %>
							<%= render :partial =>  'categories/entry', :locals => {
								:object => category 
							} %> 
						<% end %>
					</tbody>
				</table>

				
			</div> <!-- /.span8 -->
			
			
			<div class="span4">
				
				Search Category <hr />
				All Categories <hr /> 
		 
				
			</div> <!-- /.span4 -->
			
		</div> <!-- /.row -->
		
	
	</div> <!-- /.container -->

</div> <!-- /#content -->

<div class="modal fade hide" id="editEntry">
  <div class="modal-header">
    <h3>Edit Category</h3>
  </div>
  <div class="modal-body"> 
	<!-- content -->
  </div>
  <div class="modal-footer">
    <!-- <a href="javascript:;" class="btn" data-dismiss="modal">Close</a> -->
		<a  class="btn modal_closer"  >Close</a>
  </div>
</div>

<div class="modal fade hide" id="newEntry">
  <div class="modal-header">
    <h3>New Category</h3>
  </div>
  <div class="modal-body"> 
	<!-- content -->
  </div>
  <div class="modal-footer">
    <!-- <a href="javascript:;" class="btn" data-dismiss="modal">Close</a> -->
		<a  class="btn modal_closer"  >Close</a>
  </div>
</div>


<div class="hidden" id="delete_entry_form_wrapper">
  <%= form_for Vendor.new, :url =>delete_category_url , :method => :post   do |f| %>
    <%= hidden_field_tag 'object_to_destroy_id' , ''  %> 
  <% end %>
</div>


<% content_for :additional_js do %> 
	<%= javascript_include_tag "common_order/entry_creation"  	%>
<% end %>

app/views/categories/new.js.erb
$(document).ready(function(){
	  
		<% new_form = escape_javascript(  render :partial => "categories/new_object_form", :locals => {
	    :new_object => @new_object , 
			:url => categories_url 
	  })%>
 
	$("#newEntry .modal-body").append('<%= new_form %>');
	
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/categories/update_category.js.erb
$(document).ready(function(){
	// remove the spin
	
	var $modal = $("#editEntry");
	var $form = $("form", $modal );
	$form.spin(false); 
	
	// if update is successful
		// remove the form 
		// hide the modal 
		// update the row entry 
	// else
		// replace the form with the faulty one 
		// show all the error 
	
	
		<% if   @has_no_errors  %> 
			// clean the add product form
			$form.remove(); 

			<% new_entry  = escape_javascript( render :partial =>  'categories/entry', :locals => {
				:object => @category 
			} )%>

			$("#entry-<%= @category.id %>").replaceWith('<%= new_entry %>') 

			$.msgbox("Berhasil update Category: <%= @category.name %>", 
						{type: "info"});

			
			$modal.modal('hide'); 


		<% elsif  not @has_no_errors %> 
			<% new_form = escape_javascript(   render :partial => "categories/new_object_form", :locals => {
		    :new_object => @category , 
				:url => update_vendor_url(@category)  
		  })%>
			//replace the form, show the edit
			$form.replaceWith("<%= new_form %>"); 

			$.msgbox("Error dalam update Category: <%= @category.name %>", 
						{type: "error"});
		<% end %>



		jQuery('.prevent_double_submit').preventDoubleSubmit(); 
});